Repository mankomania/mankomania-client, pull requests merged in 2025-05, with the labels that each got.

#39 Feature/websocket client
  .idea/deploymentTargetSelector.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/androidTest/java/com/example/mankomaniaclient/MainActivityTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mankomaniaclient/MainActivity.kt
  app/src/main/java/com/example/mankomaniaclient/network/WebSocketService.kt
  app/src/main/res/xml/network_security_config.xml
  app/src/test/java/com/example/mankomaniaclient/NumberCheckerTest.kt
  app/src/test/java/com/example/mankomaniaclient/network/WebSocketServiceTest.kt
  gradle/libs.versions.toml
Labels: help wanted, networking

#43 Feature/loadingscreen UI
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mankomaniaclient/GameActivity.kt
  app/src/main/java/com/example/mankomaniaclient/LoadingActivity.kt
  app/src/main/java/com/example/mankomaniaclient/MainActivity.kt
  app/src/main/res/drawable/loading_screen.png
Labels: UI

#49 Feat/lobby UI
  app/build.gradle.kts
  app/src/main/java/com/example/mankomaniaclient/CreateLobbActivity.kt
  app/src/main/java/com/example/mankomaniaclient/CreateLobbyActivity.kt
  app/src/main/java/com/example/mankomaniaclient/GameActivity.kt
  app/src/main/java/com/example/mankomaniaclient/JoinLobbyActivity.kt
  app/src/main/java/com/example/mankomaniaclient/network/LobbyMessage.kt
  app/src/main/java/com/example/mankomaniaclient/network/LobbyResponse.kt
  app/src/main/java/com/example/mankomaniaclient/network/WebSocketService.kt
  app/src/main/java/com/example/mankomaniaclient/ui/screens/CreateLobbyScreen.kt
  app/src/main/java/com/example/mankomaniaclient/ui/screens/GameBoardScreen.kt
  app/src/main/java/com/example/mankomaniaclient/ui/screens/JoinLobbyScreen.kt
  gradle/libs.versions.toml
Labels: UI

#52 chore: increase Gradle JVM max heap size from 2g to 4g
  gradle.properties
Labels: setup

#50 feature/gameboard-client
  app/src/main/java/com/example/mankomaniaclient/CreateLobbyActivity.kt
  app/src/main/java/com/example/mankomaniaclient/GameActivity.kt
  app/src/main/java/com/example/mankomaniaclient/network/GameStateDto.kt
  app/src/main/java/com/example/mankomaniaclient/network/WebSocketService.kt
  app/src/main/java/com/example/mankomaniaclient/ui/components/BoardCellView.kt
  app/src/main/java/com/example/mankomaniaclient/ui/screens/GameBoardScreen.kt
  app/src/main/java/com/example/mankomaniaclient/viewmodel/GameViewModel.kt
Labels: networking
